const FILES = {
  LOAD: 'FILES_LOAD',
  LOAD_SUCCESS: 'FILES_LOAD_SUCCESS',
  LOAD_FAIL: 'FILES_LOAD_FAIL',
}

const CATEGORIES = {
  LOAD: 'CATEGORIES_LOAD',
  LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
  LOAD_FAIL: 'CATEGORIES_LOAD_FAIL',
}

export { FILES, CATEGORIES }
