const FILES = {
  LOAD: 'FILES_LOAD',
  LOAD_SUCCESS: 'FILES_LOAD_SUCCESS',
  LOAD_FAIL: 'FILES_LOAD_FAIL',
}

const CATEGORIES = {
  LOAD: 'CATEGORIES_LOAD',
  LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
  LOAD_FAIL: 'CATEGORIES_LOAD_FAIL',
}

const SUB_CATEGORIES = {
  LOAD: 'SUB_CATEGORIES_LOAD',
  LOAD_SUCCESS: 'SUB_CATEGORIES_LOAD_SUCCESS',
  LOAD_FAIL: 'SUB_CATEGORIES_LOAD_FAIL',
}

const SELECT_CATEGORY = 'SELECT_CATEGORY'
const SELECT_SUB_CATEGORY = 'SELECT_SUB_CATEGORY'
const SET_SIZE = 'SET_SIZE'
const CHANGE_PAGE = 'CHANGE_PAGE'
const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST'
const SET_REGISTER_REQUEST = 'SET_REGISTER_REQUEST'
const SELECT_A_SUB_CATEGORY = 'SELECT_A_SUB_CATEGORY'

const USER_LOGIN = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
}

const LOGOUT = 'LOGOUT'

const USER_REGISTER = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAIL: 'USER_REGISTER_FAIL',
}

const CREATE_CATEGORY = {
  CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
  CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CREATE_FAIL: 'CATEGORY_CREATE_FAIL',
}

const CREATE_SUB_CATEGORY = {
  CREATE_REQUEST: 'SUB_CATEGORY_CREATE_REQUEST',
  CREATE_SUCCESS: 'SUB_CATEGORY_CREATE_SUCCESS',
  CREATE_FAIL: 'SUB_CATEGORY_CREATE_FAIL',
}

export {
  FILES,
  CATEGORIES,
  SUB_CATEGORIES,
  SELECT_CATEGORY,
  SELECT_SUB_CATEGORY,
  SET_SIZE,
  CHANGE_PAGE,
  SET_SEARCH_TERM,
  USER_LOGIN,
  SET_LOGIN_REQUEST,
  LOGOUT,
  USER_REGISTER,
  SET_REGISTER_REQUEST,
  CREATE_CATEGORY,
  SELECT_A_SUB_CATEGORY,
  CREATE_SUB_CATEGORY,
}
